export default [
  {
    files: ["app.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        console: "readonly",
        fetch: "readonly",
        WebSocket: "readonly",
        AbortController: "readonly",
        Toastify: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        Promise: "readonly",
        JSON: "readonly",
        Array: "readonly",
        Object: "readonly",
        Number: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        Math: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        addEventListener: "readonly",
        removeEventListener: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        URL: "readonly",
        navigator: "readonly",
        confirm: "readonly",
        alert: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { "argsIgnorePattern": "^_" }],
      "no-undef": "warn",
      "no-redeclare": "warn",
      "eqeqeq": ["warn", "always"],
      "curly": ["warn", "all"],
      "no-var": "error",
      "prefer-const": "warn",
      "no-constant-binary-expression": "warn",
      "no-self-compare": "warn",
      "use-isnan": "warn",
      "valid-typeof": "warn",
    },
  },
  {
    ignores: ["assets/**", "jsconfig.json"],
  },
];